name: example-ci

on:
  # we use pull_request_target to run the CI also for forks
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]
  push:
    branches: [main]

jobs:
  functional-tests-pr:
    name: Functional Tests - PR
    if: contains(github.event.pull_request.labels.*.name, 'enable-functional-tests')
    uses: ./.github/workflows/functional-tests-workflow.yml
    strategy:
      matrix:
        aws-region: ['us-east-1', 'eu-west-1', 'eu-west-2', 'eu-central-1']
    permissions:
      id-token: write
      contents: read
    with:
      checkout-ref: ${{ github.event.pull_request.head.ref }}
      checkout-repository: ${{ github.event.pull_request.head.repo.full_name }}
      aws-region: ${{ matrix.aws-region }}
  functional-tests-main:
    name: Functional Tests - main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/functional-tests-workflow.yml
    strategy:
      matrix:
        aws-region: ['us-east-1', 'eu-west-1', 'eu-west-2', 'eu-central-1']
    permissions:
      id-token: write
      contents: read
    with:
      checkout-ref: ${{ github.ref }}
      checkout-repository: ${{ github.repository }}
      aws-region: ${{ matrix.aws-region }}
