name: "Release"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to release from"
        type: string
        default: "main"
      version:
        description: "The version to release"
        type: string
        required: true
      deploy-to:
        description: "Deploy to test or prod"
        type: environment
        default: prod
      python-version:
        description: "Python version for building and testing the build"
        type: string
        default: "3.12"

permissions:
  contents: read

jobs:
  unit-tests:
    name: 'Run unit tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - name: "Checkout ${{ github.event.repository.name }}@${{ inputs.branch }}"
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: "Setup `hatch`"
        uses: dbt-labs/dbt-adapters/.github/actions/setup-hatch@main
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Test with pytest"
        run: hatch run unit-tests
        working-directory: ./dbt-athena

  integration-tests:
    name: "Run integration tests"
    uses: ./.github/workflows/functional-tests-workflow.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      checkout-ref: ${{ inputs.branch }}

  build-release:
    name: "Build release"
    needs: [unit-tests, integration-tests]
    runs-on: ubuntu-latest
    outputs:
      archive-name: ${{ steps.archive.outputs.name }}
    steps:
      - name: "Checkout ${{ github.event.repository.name }}@${{ inputs.branch }}"
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          persist-credentials: false

      - name: "Setup `hatch`"
        uses: dbt-labs/dbt-adapters/.github/actions/setup-hatch@main
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Set archive name"
        id: archive
        run: |
          archive_name=${{ github.event.repository.name }}-${{ inputs.version }}-${{ inputs.deploy-to }}
          echo "name=$archive_name" >> $GITHUB_OUTPUT

      - name: "Build ${{ github.event.repository.name }}"
        uses: dbt-labs/dbt-adapters/.github/actions/build-hatch@main
        with:
          working-dir: ./dbt-athena
          archive-name: ${{ steps.archive.outputs.name }}

  pypi-release:
    name: "PyPI release"
    if: ${{ !failure() && !cancelled() }}
    runs-on: ubuntu-latest
    needs: build-release
    environment:
      name: ${{ inputs.deploy-to }}
      url: ${{ vars.PYPI_PROJECT_URL }}
    permissions:
      # this permission is required for trusted publishing
      # see https://github.com/marketplace/actions/pypi-publish
      id-token: write
    steps:
      - name: "Publish to PyPI"
        uses: dbt-labs/dbt-adapters/.github/actions/publish-pypi@main
        with:
          repository-url: ${{ vars.PYPI_REPOSITORY_URL }}
          archive-name: ${{ needs.build-release.outputs.archive-name }}
